# Generated by Django 6.0.1 on 2026-01-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='title',
            new_name='title_primary',
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_secondary',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
