# Generated by Django 6.0.1 on 2026-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_featuresection_featureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
