# Generated by Django 6.0.1 on 2026-01-12 09:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_featuresection_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Platform', max_length=200)),
                ('subtitle', models.CharField(default='We are innovative educational institution to the creation of the student', max_length=300)),
                ('description', ckeditor.fields.RichTextField()),
                ('button_text', models.CharField(default='Browse All Courses', max_length=100)),
                ('button_link', models.CharField(default='/courses/', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/about/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_title', models.CharField(default='Our Team', max_length=200)),
                ('team_description', models.TextField(default='Our team consists of certified IT professionals with expertise in network security, cloud computing, software development, and technical support. With decades of combined experience, we provide strategic IT guidance and technical support tailored to your business needs.')),
            ],
            options={
                'verbose_name': 'Home About Section',
                'verbose_name_plural': 'Home About Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
