# Generated by Django 6.0.1 on 2026-01-12 09:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_homeaboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutsection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
