# Generated by Django 6.0.1 on 2026-01-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_homeaboutsection_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaboutsection',
            options={'verbose_name': 'Home About Section', 'verbose_name_plural': 'Home About Sections'},
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/about/', verbose_name='About Section Image'),
        ),
    ]
