# Generated by Django 6.0.1 on 2026-01-12 11:45

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_coursecategory_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.CharField(blank=True, help_text="Instructor names, comma separated (e.g., 'Saran, Deepan')", max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='What students will learn (use bullet points)'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Requirements before taking this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL for course preview'),
        ),
        migrations.AddField(
            model_name='course',
            name='tagline',
            field=models.TextField(blank=True, help_text='Short catchy tagline shown below course title', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='total_projects',
            field=models.IntegerField(default=0, help_text='Number of projects included'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_resources',
            field=models.IntegerField(default=0, help_text='Number of downloadable resources'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_videos',
            field=models.IntegerField(default=0, help_text='Total number of video lessons'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Mark if this lesson is free preview'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_title',
            field=models.CharField(blank=True, help_text='Module/section title for grouping', max_length=200),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text="e.g., 'Senior Developer', 'Data Scientist'", max_length=200)),
                ('bio', ckeditor.fields.RichTextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Main instructor for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='lms.instructor'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
