# Generated by Django 6.0.1 on 2026-02-12 11:13

from django.db import migrations, models
from datetime import timedelta  # Add this import


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_remove_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(
                default=timedelta(0),  # Add this default
                blank=True,
                null=True
            ),
        ),
    ]