# Generated by Django 6.0.1 on 2026-01-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('row_number', models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='lms.course')),
            ],
            options={
                'verbose_name': 'Course Skill',
                'verbose_name_plural': 'Course Skills',
                'ordering': ['row_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='lms.course')),
            ],
            options={
                'verbose_name': 'Course Tool',
                'verbose_name_plural': 'Course Tools',
                'ordering': ['tool_name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_days', to='lms.course')),
            ],
            options={
                'verbose_name': 'Curriculum Day',
                'verbose_name_plural': 'Curriculum Days',
                'ordering': ['day_number'],
            },
        ),
    ]
