# Generated by Django 6.0.1 on 2026-01-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_alter_payment_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseskill',
            options={'ordering': ['row_number', 'order']},
        ),
        migrations.AlterModelOptions(
            name='coursetool',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='curriculumday',
            options={'ordering': ['order', 'day_number'], 'verbose_name': 'Curriculum Day', 'verbose_name_plural': 'Curriculum Days'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddField(
            model_name='curriculumday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='curriculumday',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Free for all users'),
        ),
        migrations.AddField(
            model_name='curriculumday',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Allow preview'),
        ),
        migrations.AddField(
            model_name='curriculumday',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of display'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.CharField(blank=True, help_text='Instructor names, comma separated', max_length=300),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='team_description',
            field=models.TextField(default='Our team consists of certified IT professionals with expertise in network security, cloud computing, software development, and technical support.'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('free', 'Free Enrollment'), ('paid', 'Paid Enrollment'), ('trial', 'Trial Period')], default='free', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct URL'), ('embed', 'Embed Code')], default='youtube', max_length=20)),
                ('duration', models.CharField(help_text='Format: HH:MM:SS or MM:SS', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_purchase', models.BooleanField(default=True, verbose_name='Requires purchase')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Allow preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lms.curriculumday')),
            ],
            options={
                'verbose_name': 'Video Lesson',
                'verbose_name_plural': 'Video Lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('watched_duration', models.IntegerField(default=0, help_text='Total seconds watched')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.videolesson')),
            ],
            options={
                'verbose_name': 'User Video Progress',
                'verbose_name_plural': 'User Video Progress',
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
