# Generated by Django 6.0.1 on 2026-01-14 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_payment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='order',
            new_name='total_learners',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='photo',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preview_video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_projects',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_resources',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_videos',
        ),
        migrations.AlterUniqueTogether(
            name='curriculumday',
            unique_together={('course', 'day_number')},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='website_url',
        ),
        migrations.AddField(
            model_name='course',
            name='access_level',
            field=models.CharField(default='Anyone Can learn (IT/Non IT)', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='certification_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(default=0, help_text='Total course duration in hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.CharField(default='Tamil, English', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='payment_type',
            field=models.CharField(default='1 Time Payment', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(default='', help_text='Comma-separated list of skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tools_learned',
            field=models.TextField(default='', help_text='Comma-separated list of tools'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='lms.coursecategory'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tools', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Make this day free for all users'),
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='title',
            field=models.CharField(blank=True, help_text='Optional day title', max_length=200),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lms.videolesson'),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='watched_duration',
            field=models.IntegerField(default=0, help_text='Duration watched in seconds'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='curriculum_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to='lms.curriculumday'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='URL to video file or embed link')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('duration', models.CharField(help_text='Format: MM:SS or HH:MM:SS', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('order', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
                ('curriculum_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lms.curriculumday')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='curriculumday',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='curriculumday',
            name='is_preview',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', to='lms.instructor'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='lms.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('watch_time_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lms.video')),
            ],
            options={
                'verbose_name': 'Video Progress',
                'verbose_name_plural': 'Video Progress',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
