# Generated by Django 6.0.1 on 2026-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_remove_course_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.TextField(help_text='Comma-separated skills (e.g., Python, Django, React, HTML, CSS)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tools_learned',
            field=models.TextField(help_text='Comma-separated tools (e.g., VSCode, GitHub, Figma, Docker)'),
        ),
    ]
