# Generated by Django 6.0.1 on 2026-01-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_alter_course_skills_alter_course_tools_learned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lms.video'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='video',
        ),
        migrations.DeleteModel(
            name='VideoLesson',
        ),
        migrations.DeleteModel(
            name='VideoProgress',
        ),
    ]
