# Generated by Django 6.0.1 on 2026-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_alter_uservideoprogress_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Join World's largest learning platform today", max_length=200)),
                ('highlight_text', models.CharField(default="World's largest", max_length=50)),
                ('subtitle', models.CharField(default='Start learning by registering for free', max_length=200)),
                ('button_text', models.CharField(default='Sign up for Free', max_length=50)),
                ('button_url', models.URLField(default='/signup/')),
                ('image', models.ImageField(upload_to='home_banner/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of display if multiple banners exist')),
            ],
            options={
                'verbose_name': 'Home Page Banner',
                'verbose_name_plural': 'Home Page Banners',
                'ordering': ['order'],
            },
        ),
    ]
