# Generated by Django 6.0.1 on 2026-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='button_url',
            field=models.CharField(help_text='Enter a relative URL like /signup/', max_length=200),
        ),
    ]
