# Generated by Django 6.0.1 on 2026-01-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_homebanner_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
