# Generated by Django 6.0.1 on 2026-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_instructor_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
