# Generated by Django 6.0.1 on 2026-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_type',
            field=models.CharField(default='One Time Payment', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='total_learners',
            field=models.CharField(default='100+', max_length=50),
        ),
    ]
