# Generated by Django 6.0.1 on 2026-01-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_course_payment_type_course_total_learners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_type',
            field=models.CharField(default='One Time', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_learners',
            field=models.CharField(default='100', max_length=50),
        ),
    ]
