# Generated by Django 6.0.1 on 2026-01-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_alter_course_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_learners',
            field=models.CharField(max_length=50),
        ),
    ]
