# Generated by Django 6.0.1 on 2026-01-19 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_alter_course_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoprogress',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='watched_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
