# Generated by Django 6.0.1 on 2026-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_alter_uservideoprogress_progress_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideoprogress',
            old_name='progress_percentage',
            new_name='watched_percentage',
        ),
    ]
