# Generated by Django 6.0.1 on 2026-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_question_answer_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_quiz_attempt_id',
            field=models.CharField(blank=True, help_text='ID of the quiz attempt that passed', max_length=100, null=True),
        ),
    ]
