# Generated by Django 6.0.1 on 2026-01-21 05:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_courseprogress_last_quiz_attempt_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course Review', 'verbose_name_plural': 'Course Reviews'},
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='comment',
            new_name='review',
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursereview',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo', null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='is_approved',
        ),
    ]
