# Generated by Django 6.0.1 on 2026-01-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_alter_coursereview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='generated_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
