# Generated by Django 6.0.1 on 2026-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_certificate_generated_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_signature',
            new_name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
