# Generated by Django 6.0.1 on 2026-01-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_rename_razorpay_signature_payment_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Figma, Photoshop', max_length=100)),
                ('description', models.TextField(blank=True, help_text='What this tool is used for')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome class, e.g., 'fab fa-figma'", max_length=100)),
                ('icon_image', models.ImageField(blank=True, help_text='Custom icon image', null=True, upload_to='tool_icons/')),
                ('download_url', models.URLField(blank=True, help_text='Link to download or learn more')),
                ('is_required', models.BooleanField(default=True, help_text='Is this tool required or optional?')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('category', models.CharField(choices=[('design', 'Design Tools'), ('development', 'Development Tools'), ('video', 'Video Editing'), ('data', 'Data Science'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tools needed for this entire course', related_name='courses', to='lms.tool'),
        ),
        migrations.AddField(
            model_name='curriculumday',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tools introduced or needed for this day', related_name='curriculum_days', to='lms.tool'),
        ),
        migrations.AddField(
            model_name='video',
            name='tools_needed',
            field=models.ManyToManyField(blank=True, help_text='Specific tools needed for this video', related_name='videos', to='lms.tool'),
        ),
    ]
