# Generated by Django 6.0.1 on 2026-01-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0039_tool_course_tools_curriculumday_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload course brochure/syllabus PDF', null=True, upload_to='course_brochures/'),
        ),
    ]
